#!/bin/sh
cmd=${0##/*/}
exe=`echo $cmd | sed 's/.\///'`
cr=${1}
script_dir=/ccshare/linux/c_scripts

usage()
{
   echo "Usage $exe cr_num"
   echo "Run perl script to create a new view for the specified CR number."
   echo
   echo "example:"
   echo "   $exe 8179"
   echo
}

ccv ()
{
    $script_dir/*"$cr"_view.pl 2> /dev/null | grep "Dynamic view"
}

if [ -z $1 ]; then
   usage
   exit 1
fi

shift $(($OPTIND - 1))

$exe $*
