#!/bin/sh
date_stamp=`date +%m%d%y`
basedir=/ccshare/linux/c_files/monty/builds/
view_name=`echo $CLEARCASE_ROOT | sed 's/\/view\/monty_qt_//g'`

if [ -z $1 ]; then 
#    echo "Not adding a suffix to the file name"
    echo "Adding current date to file name"
    tag=$date_stamp
else
    tag=$date_stamp"_"$1
fi

if [ "$2" = "pb" ]; then
   #Prebuilt-package
    cd /vobs/vendor/digia/qt; make S=XIP913 prebuilt-package
fi
pre=/vobs/vendor/digia/qt/build/XIP913/5.4.0/XIP913_Qt.tar.gz
pkg="$view_name""$tag".tar.gz

hex=/vobs/src_tree/build/link/appcreate/gandalf_dev_debug.bin
bin="$view_name""$tag".bin
udf=/vobs/src_tree/build/link/appcreate/gandalf_dev_debug.update
upd="$view_name"_"$tag".update

csfile="$view_name"_"$tag".cs

if [ "$1" = "cfg" ]; then
    cleartool catcs > $basedir/$csfile
    exit
fi

cleartool catcs > $basedir/$csfile
#cp $hex $basedir/$bin
cp $udf $basedir/$upd
if [ "$2" = "pb" ]; then
    cp $pre $basedir/$pkg
fi
