#!/bin/sh
cmd=${0##/*/}
exe=`echo $cmd | sed 's/.\///'`

cr=$1
branch=$2

config_dir='/ccshare/linux/c_spec/'
cr_review='/ccshare/linux/cc_tools/cr_review'

usage()
{
   echo "Usage $exe cr_num [d]"
   echo "Run code review script on the specified CR number."
   echo
   echo "   [d] Passes the 'd' option for a branch compare" 
   echo
   echo "examples:"
   echo "   $exe 8179"
   echo "   $exe 8179 d"
   echo
}

crev ()
{
#    cr=`echo $1 | sed 's/cr//'`
    config_spec=$config_dir*cr$cr*.txt

    if [ -n "$cr" ]; then
        $cr_review $config_spec $branch > /dev/null 2>&1
        rm cr_sh.$cr
    else
        usage
        exit 1
    fi
}

if [ -z $1 ]; then
   usage
   exit 1
fi

shift $(($OPTIND - 1))

$exe $*
