#!/bin/sh
date_stamp=`date +%m%d%y`
basedir=/ccshare/linux/c_files/monty/builds/
#view_name=`echo $CLEARCASE_ROOT | sed 's/\/view\///g'`
view_name=`echo $CLEARCASE_ROOT | sed 's/\/view\/monty_//g' | rev | cut -c 4- | rev`


if [ -z $1 ]; then 
    echo "Not adding a suffix to the file name"
else
    tag="_"$1
fi

hex=/vobs/src_tree/build/link/appcreate/gandalf_dev_debug.bin
bin="$view_name""$tag".bin
csfile="$view_name""$tag".cs

if [ "$1" = "cfg" ]; then
    cleartool catcs > $basedir/$csfile
    exit
fi

cleartool catcs > $basedir/$csfile
cp $hex $basedir/$bin
