#!/usr/bin/expect -f

################################################################################
# Expect script to telnet to a given 
# ip address and program flash.
# 
# Author          : Montgomery Groff
# Original Author : Vijay.Jayaraman
# Version         : 1.0
# Last Updated    : 07-06-2011
#
# 1.0 - Copied tnet script and modified for running from nfs on the box
#
set box_run_version "1.0"
################################################################################

if {$argc != 1} {
        puts "Usage: box_run <ip address>"
        puts "Ex: box_run 192.168.1.202"
        exit
}

# Un-comment "log_user 0" for silent operation
log_user 0
set timeout 2
set ip [lindex $argv 0]
set prompt "~ #"

################################################################################
# User customizable variables - Please customize this for your setup.
################################################################################
set ip_address       "192.168.1.1"
set home_dir         "/home/monty/stb/"
################################################################################

set mount_cmd        "mount -o nolock $ip_address:$home_dir /home \r"
set kill_cmd         "kill -s SIGUSR2 1 \r"

puts "Connecting to stb at $ip, please wait."

for {set x 0} {$x<120} {incr x} {
    # Open a telnet session to a remote server, and wait for a username prompt.
    spawn telnet $ip

    # Expect a timeout and then retry again.
    expect {
        timeout    {continue}
 	"login:"   {send "root\r"; expect $prompt; send $kill_cmd; break}
    }
}

puts "Kill command sent, proceed to mount nfs."

# Mount to nfs share on host
expect $prompt
send $mount_cmd

interact
