#!/usr/bin/expect

################################################################################
# Expect script to telnet to a given 
# ip address and kill a given process.
# 
# Original Author : Vijay.Jayaraman
# Version         : 1.4
# Last Updated    : 06-22-2011
#
# 1.4 - Pulling out user customizable variables to top for easy modification.
# 1.3 - Unmounting /var/mnt/drivers as well to be safe.
# 1.2 - Unmounting /usr/local before mounting it again.
# 1.1 - Fixed bug with export command.
#
set tnet_version "1.4"
################################################################################

#puts "tnet script version: $tnet_version"

if {$argc != 1} {
        puts "Usage: tnet <ip address>"
        puts "Ex: tnet 192.168.1.202"
        exit
}

log_user 0
set timeout 2
set ip [lindex $argv 0]
set prompt "~ #"

################################################################################
# User customizable variables - Please customize this for your setup.
################################################################################
set ip_address       "192.168.100.100"
set home_dir         "/Users/monty/stb"
################################################################################

set mount_cmd    "mount -o nolock $ip_address:$home_dir /home \r"
set kill_cmd     "kill -s SIGUSR2 1"

puts "Connecting to stb at $ip, please wait."

for {set x 0} {$x<120} {incr x} {
    # Open a telnet session to a remote server, and wait for a username prompt.
    spawn telnet $ip

    # Expect a timeout and then retry again.
    expect {
        timeout    {continue}
 	"login:"   {send "root\r"; expect $prompt; break}
    }
}

expect $prompt
send $mount_cmd

interact
