#!/bin/sh
cmd=${0##/*/}
exe=`echo $cmd | sed 's/.\///'`

type=$2

mgrep ()
{
    if [ -z "$type" ]; then
        type='*'
    else
        type="$type"
    fi
    set -x    #echo on
    grep -rn --include=$type --color=auto $1 
}

$exe $*
