#!/bin/sh
ACTION='cp -p'
DIR=/ccshare/linux/c_files/xip/dev-release/lincoln
DATE=$1
RM=$2

if [ -z $1 ]; then
    echo "Usage: xiparchive <date> <directory>" 
    echo 
    exit 1;
fi

cd $DIR/proposed

if [ -z $DATE ]; then
    echo "Usage: xiparchive <date> <directory>" 
    echo 
    echo "Here is the current file list"
    ls -l
    exit 1;
fi

$ACTION *112*$DATE* $DIR/112/ #> /dev/null 2>&1
$ACTION *110_*$DATE* $DIR/110/ #> /dev/null 2>&1
$ACTION *110C*$DATE* $DIR/110cr/ #> /dev/null 2>&1
$ACTION *813*$DATE* $DIR/813/ #> /dev/null 2>&1
$ACTION *913*$DATE* $DIR/913/ #> /dev/null 2>&1

if [ ! -z $RM ]; then
    $RM *$DATE* 
fi

ls -l

