#!/bin/bash
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee -a ~/Library/Logs/herbie-lou-update.log)
exec 2> >(tee -a ~/Library/Logs/herbie-lou-update.log >&2)

#!/bin/bash
src_dir="/Volumes/monty/"
dst_dir="/Users/monty/"
music_dir="Music/iTunes/iTunes Media/"
image_dir="Pictures/"
#EXCL="--exclude *.aplibrary"

src_music=$src_dir$music_dir
dst_music=$dst_dir$music_dir
src_image=$src_dir$image_dir
dst_image=$dst_dir$image_dir

usage()
{
    echo " Usage: ./herbie-lou-update"
    echo ""
}     

if [ ! -d $src_dir ]; then
    open afp://Herbie/monty
    sleep 10
fi

if [ -d $src_dir ]; then
    echo "--------"
    echo `date`
    echo "## Update $dst_music using rsync"
    echo "rsync -av --delete $src_music $dst_music"
    time rsync --dry-run -av --delete "$src_music" "$dst_music"
    echo "## Update $dst_image using rsync"
    echo "rsync -av --delete $src_image $dst_image"
    time rsync --dry-run -av --delete --exclude 'Photos Library.photoslibrary' $src_image $dst_image
else
    echo "$src_dir Not Mounted"
fi
