#!/bin/bash
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee -a ~/Library/Logs/remote-bowie-lou-update.log)
exec 2> >(tee -a ~/Library/Logs/remote-bowie-lou-update.log >&2)

#!/bin/bash
src_dir="bowie.273244040.members.btmm.icloud.com:/Users/monty/"
dst_dir="/Users/monty/"
music_dir="Music/iTunes/"
image_dir="Pictures/"
#EXCL="--exclude *.aplibrary"

src_music=$src_dir$music_dir
dst_music=$dst_dir$music_dir
src_image=$src_dir$image_dir
dst_image=$dst_dir$image_dir

usage()
{
    echo " Usage: ./bowie-lou-update"
    echo ""
}     

#if [ ! -d $src_dir ]; then
#    open afp://Bowie.local/monty
#    sleep 10
#fi

#if [ -d $src_dir ]; then
    echo "--------"
    echo `date`
    echo "## Update $dst_music using rsync"
    echo "rsync -av --delete --stats $src_music $dst_music"
    time rsync --dry-run -e ssh -av --delete --stats "$src_music" "$dst_music"
    echo "## Update $dst_image using rsync"
    echo "rsync -av --delete --sats $src_image $dst_image"
    time rsync --dry-run -e ssh -av --delete --stats --exclude 'Photos Library.photoslibrary' $src_image $dst_image
#else
#    echo "$src_dir Not Mounted"
#fi
