#!/bin/bash
param=$1
exclude="--exclude *Library.photoslibrary"
exclude2="--exclude *.itl --exclude *.itdb --exclude *.xml --exclude 'Album Artwork'"

if [ "$1" = "local" ]; then
    param=" "
    src_dir="/Volumes/monty/"
    get_pw=`security 2>&1 >/dev/null find-generic-password -ga monty |ruby -e 'print $1 if STDIN.gets =~ /^password: "(.*)"$/'`

    mkdir /Volumes/monty
    mount_afp afp://monty:"$get_pw"@Bowie.local/monty /Volumes/monty
    #open -W afp://Bowie.local/monty
    ret=$?
    if [ $ret != 0 ]; then
        echo "error mounting $src_dir"
#        exit 1
    fi
else
    src_dir="bowie.273244040.members.btmm.icloud.com:/Users/monty/"
fi
dst_dir="/Users/monty/"
music_dir="Music/iTunes/iTunes\ Media/Music/"
image_dir="Pictures/"

src_music=$src_dir$music_dir
dst_music=$dst_dir$music_dir
src_image=$src_dir$image_dir
dst_image=$dst_dir$image_dir

mv ~/Library/Logs/bowie-lou-update.log ~/Library/Logs/bowie-lou-update.prev
exec &> >(tee -a ~/Library/Logs/bowie-lou-update.log)
echo -e "\n-------- `date` --------"
set -x
time rsync $param -e ssh -av --stats "$src_music" "$dst_music"
#time rsync $param -e ssh -av --delete --stats $exclude "$src_image" "$dst_image"
set +x

if [ "$1" = "local" ]; then
    umount /Volumes/monty
fi